package testing.saker.android.tests;

import java.util.LinkedHashSet;
import java.util.Set;
import java.util.TreeMap;

import saker.build.file.path.SakerPath;
import saker.build.file.provider.LocalFileProvider;
import saker.build.thirdparty.saker.util.ObjectUtils;
import testing.saker.build.tests.EnvironmentTestCaseConfiguration;
import testing.saker.nest.util.NestRepositoryCachingEnvironmentTestCase;

public abstract class BaseAndroidTestCase extends NestRepositoryCachingEnvironmentTestCase {
	@Override
	protected Set<EnvironmentTestCaseConfiguration> getTestConfigurations() {
		LinkedHashSet<EnvironmentTestCaseConfiguration> result = new LinkedHashSet<>();
		for (EnvironmentTestCaseConfiguration tcc : super.getTestConfigurations()) {
			TreeMap<String, String> userparams = ObjectUtils.newTreeMap(tcc.getEnvironmentUserParameters());
			userparams.put("saker.android.sdk.install.location",
					testParameters.get("AndroidSDKLocationEnvironmentUserParameter"));
			result.add(EnvironmentTestCaseConfiguration.builder(tcc).setEnvironmentUserParameters(userparams).build());
		}
		return result;
	}

	@Override
	protected String getRepositoryStorageConfiguration() {
		//TODO exclude the saker.android bundles from the server storage
		return "[:params, :server]";
	}

	public static void touchLocalFileForIncrementalTesting(SakerPath path) {
		//touch the file at the given path and all of its parents to work around bugs in saker.java.testing
		//this ensures that the incremental test runner won't delete the output file generated by an external process
		//when accessed by the test
		//TODO remove this entirely as saker.java.testing is fixed.
		while (path.getNameCount() > 0) {
			try {
				LocalFileProvider.getInstance().getFileAttributes(path);
			} catch (Exception e) {
			}
			path = path.getParent();
		}
	}
}
